package cn.besbing.dao;

import cn.besbing.pojo.HisBasicReport;
import cn.besbing.pojo.HisBasicReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HisBasicReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HIS_BASIC_REPORT
     *
     * @mbg.generated Wed Nov 06 13:44:48 CST 2019
     */
    long countByExample(HisBasicReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HIS_BASIC_REPORT
     *
     * @mbg.generated Wed Nov 06 13:44:48 CST 2019
     */
    int deleteByExample(HisBasicReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HIS_BASIC_REPORT
     *
     * @mbg.generated Wed Nov 06 13:44:48 CST 2019
     */
    int deleteByPrimaryKey(String pkHisReport);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HIS_BASIC_REPORT
     *
     * @mbg.generated Wed Nov 06 13:44:48 CST 2019
     */
    int insert(HisBasicReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HIS_BASIC_REPORT
     *
     * @mbg.generated Wed Nov 06 13:44:48 CST 2019
     */
    int insertSelective(HisBasicReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HIS_BASIC_REPORT
     *
     * @mbg.generated Wed Nov 06 13:44:48 CST 2019
     */
    List<HisBasicReport> selectByExample(HisBasicReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HIS_BASIC_REPORT
     *
     * @mbg.generated Wed Nov 06 13:44:48 CST 2019
     */
    HisBasicReport selectByPrimaryKey(String pkHisReport);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HIS_BASIC_REPORT
     *
     * @mbg.generated Wed Nov 06 13:44:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") HisBasicReport record, @Param("example") HisBasicReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HIS_BASIC_REPORT
     *
     * @mbg.generated Wed Nov 06 13:44:48 CST 2019
     */
    int updateByExample(@Param("record") HisBasicReport record, @Param("example") HisBasicReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HIS_BASIC_REPORT
     *
     * @mbg.generated Wed Nov 06 13:44:48 CST 2019
     */
    int updateByPrimaryKeySelective(HisBasicReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HIS_BASIC_REPORT
     *
     * @mbg.generated Wed Nov 06 13:44:48 CST 2019
     */
    int updateByPrimaryKey(HisBasicReport record);
}