package cn.besbing.dao;

import cn.besbing.pojo.LsUsersInfo;
import cn.besbing.pojo.LsUsersInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LsUsersInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    long countByExample(LsUsersInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    int deleteByExample(LsUsersInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    int deleteByPrimaryKey(String pkPsndoc);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    int insert(LsUsersInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    int insertSelective(LsUsersInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    List<LsUsersInfo> selectByExample(LsUsersInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    LsUsersInfo selectByPrimaryKey(String pkPsndoc);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") LsUsersInfo record, @Param("example") LsUsersInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    int updateByExample(@Param("record") LsUsersInfo record, @Param("example") LsUsersInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    int updateByPrimaryKeySelective(LsUsersInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    int updateByPrimaryKey(LsUsersInfo record);
}