package cn.besbing.dao;

import cn.besbing.pojo.SmUser;
import cn.besbing.pojo.SmUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    long countByExample(SmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    int deleteByExample(SmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    int deleteByPrimaryKey(String cuserid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    int insert(SmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    int insertSelective(SmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    List<SmUser> selectByExample(SmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    SmUser selectByPrimaryKey(String cuserid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") SmUser record, @Param("example") SmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    int updateByExample(@Param("record") SmUser record, @Param("example") SmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    int updateByPrimaryKeySelective(SmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    int updateByPrimaryKey(SmUser record);
}