package cn.besbing.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class LsUsersInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public LsUsersInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkPsndocIsNull() {
            addCriterion("PK_PSNDOC is null");
            return (Criteria) this;
        }

        public Criteria andPkPsndocIsNotNull() {
            addCriterion("PK_PSNDOC is not null");
            return (Criteria) this;
        }

        public Criteria andPkPsndocEqualTo(String value) {
            addCriterion("PK_PSNDOC =", value, "pkPsndoc");
            return (Criteria) this;
        }

        public Criteria andPkPsndocNotEqualTo(String value) {
            addCriterion("PK_PSNDOC <>", value, "pkPsndoc");
            return (Criteria) this;
        }

        public Criteria andPkPsndocGreaterThan(String value) {
            addCriterion("PK_PSNDOC >", value, "pkPsndoc");
            return (Criteria) this;
        }

        public Criteria andPkPsndocGreaterThanOrEqualTo(String value) {
            addCriterion("PK_PSNDOC >=", value, "pkPsndoc");
            return (Criteria) this;
        }

        public Criteria andPkPsndocLessThan(String value) {
            addCriterion("PK_PSNDOC <", value, "pkPsndoc");
            return (Criteria) this;
        }

        public Criteria andPkPsndocLessThanOrEqualTo(String value) {
            addCriterion("PK_PSNDOC <=", value, "pkPsndoc");
            return (Criteria) this;
        }

        public Criteria andPkPsndocLike(String value) {
            addCriterion("PK_PSNDOC like", value, "pkPsndoc");
            return (Criteria) this;
        }

        public Criteria andPkPsndocNotLike(String value) {
            addCriterion("PK_PSNDOC not like", value, "pkPsndoc");
            return (Criteria) this;
        }

        public Criteria andPkPsndocIn(List<String> values) {
            addCriterion("PK_PSNDOC in", values, "pkPsndoc");
            return (Criteria) this;
        }

        public Criteria andPkPsndocNotIn(List<String> values) {
            addCriterion("PK_PSNDOC not in", values, "pkPsndoc");
            return (Criteria) this;
        }

        public Criteria andPkPsndocBetween(String value1, String value2) {
            addCriterion("PK_PSNDOC between", value1, value2, "pkPsndoc");
            return (Criteria) this;
        }

        public Criteria andPkPsndocNotBetween(String value1, String value2) {
            addCriterion("PK_PSNDOC not between", value1, value2, "pkPsndoc");
            return (Criteria) this;
        }

        public Criteria andWorkCodeIsNull() {
            addCriterion("WORK_CODE is null");
            return (Criteria) this;
        }

        public Criteria andWorkCodeIsNotNull() {
            addCriterion("WORK_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andWorkCodeEqualTo(String value) {
            addCriterion("WORK_CODE =", value, "workCode");
            return (Criteria) this;
        }

        public Criteria andWorkCodeNotEqualTo(String value) {
            addCriterion("WORK_CODE <>", value, "workCode");
            return (Criteria) this;
        }

        public Criteria andWorkCodeGreaterThan(String value) {
            addCriterion("WORK_CODE >", value, "workCode");
            return (Criteria) this;
        }

        public Criteria andWorkCodeGreaterThanOrEqualTo(String value) {
            addCriterion("WORK_CODE >=", value, "workCode");
            return (Criteria) this;
        }

        public Criteria andWorkCodeLessThan(String value) {
            addCriterion("WORK_CODE <", value, "workCode");
            return (Criteria) this;
        }

        public Criteria andWorkCodeLessThanOrEqualTo(String value) {
            addCriterion("WORK_CODE <=", value, "workCode");
            return (Criteria) this;
        }

        public Criteria andWorkCodeLike(String value) {
            addCriterion("WORK_CODE like", value, "workCode");
            return (Criteria) this;
        }

        public Criteria andWorkCodeNotLike(String value) {
            addCriterion("WORK_CODE not like", value, "workCode");
            return (Criteria) this;
        }

        public Criteria andWorkCodeIn(List<String> values) {
            addCriterion("WORK_CODE in", values, "workCode");
            return (Criteria) this;
        }

        public Criteria andWorkCodeNotIn(List<String> values) {
            addCriterion("WORK_CODE not in", values, "workCode");
            return (Criteria) this;
        }

        public Criteria andWorkCodeBetween(String value1, String value2) {
            addCriterion("WORK_CODE between", value1, value2, "workCode");
            return (Criteria) this;
        }

        public Criteria andWorkCodeNotBetween(String value1, String value2) {
            addCriterion("WORK_CODE not between", value1, value2, "workCode");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("USER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("USER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("USER_NAME =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("USER_NAME <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("USER_NAME >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NAME >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("USER_NAME <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("USER_NAME <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("USER_NAME like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("USER_NAME not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("USER_NAME in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("USER_NAME not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("USER_NAME between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("USER_NAME not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserSexIsNull() {
            addCriterion("USER_SEX is null");
            return (Criteria) this;
        }

        public Criteria andUserSexIsNotNull() {
            addCriterion("USER_SEX is not null");
            return (Criteria) this;
        }

        public Criteria andUserSexEqualTo(BigDecimal value) {
            addCriterion("USER_SEX =", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexNotEqualTo(BigDecimal value) {
            addCriterion("USER_SEX <>", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexGreaterThan(BigDecimal value) {
            addCriterion("USER_SEX >", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_SEX >=", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexLessThan(BigDecimal value) {
            addCriterion("USER_SEX <", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexLessThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_SEX <=", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexIn(List<BigDecimal> values) {
            addCriterion("USER_SEX in", values, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexNotIn(List<BigDecimal> values) {
            addCriterion("USER_SEX not in", values, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_SEX between", value1, value2, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_SEX not between", value1, value2, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserPasswdIsNull() {
            addCriterion("USER_PASSWD is null");
            return (Criteria) this;
        }

        public Criteria andUserPasswdIsNotNull() {
            addCriterion("USER_PASSWD is not null");
            return (Criteria) this;
        }

        public Criteria andUserPasswdEqualTo(String value) {
            addCriterion("USER_PASSWD =", value, "userPasswd");
            return (Criteria) this;
        }

        public Criteria andUserPasswdNotEqualTo(String value) {
            addCriterion("USER_PASSWD <>", value, "userPasswd");
            return (Criteria) this;
        }

        public Criteria andUserPasswdGreaterThan(String value) {
            addCriterion("USER_PASSWD >", value, "userPasswd");
            return (Criteria) this;
        }

        public Criteria andUserPasswdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_PASSWD >=", value, "userPasswd");
            return (Criteria) this;
        }

        public Criteria andUserPasswdLessThan(String value) {
            addCriterion("USER_PASSWD <", value, "userPasswd");
            return (Criteria) this;
        }

        public Criteria andUserPasswdLessThanOrEqualTo(String value) {
            addCriterion("USER_PASSWD <=", value, "userPasswd");
            return (Criteria) this;
        }

        public Criteria andUserPasswdLike(String value) {
            addCriterion("USER_PASSWD like", value, "userPasswd");
            return (Criteria) this;
        }

        public Criteria andUserPasswdNotLike(String value) {
            addCriterion("USER_PASSWD not like", value, "userPasswd");
            return (Criteria) this;
        }

        public Criteria andUserPasswdIn(List<String> values) {
            addCriterion("USER_PASSWD in", values, "userPasswd");
            return (Criteria) this;
        }

        public Criteria andUserPasswdNotIn(List<String> values) {
            addCriterion("USER_PASSWD not in", values, "userPasswd");
            return (Criteria) this;
        }

        public Criteria andUserPasswdBetween(String value1, String value2) {
            addCriterion("USER_PASSWD between", value1, value2, "userPasswd");
            return (Criteria) this;
        }

        public Criteria andUserPasswdNotBetween(String value1, String value2) {
            addCriterion("USER_PASSWD not between", value1, value2, "userPasswd");
            return (Criteria) this;
        }

        public Criteria andUserActiveIsNull() {
            addCriterion("USER_ACTIVE is null");
            return (Criteria) this;
        }

        public Criteria andUserActiveIsNotNull() {
            addCriterion("USER_ACTIVE is not null");
            return (Criteria) this;
        }

        public Criteria andUserActiveEqualTo(BigDecimal value) {
            addCriterion("USER_ACTIVE =", value, "userActive");
            return (Criteria) this;
        }

        public Criteria andUserActiveNotEqualTo(BigDecimal value) {
            addCriterion("USER_ACTIVE <>", value, "userActive");
            return (Criteria) this;
        }

        public Criteria andUserActiveGreaterThan(BigDecimal value) {
            addCriterion("USER_ACTIVE >", value, "userActive");
            return (Criteria) this;
        }

        public Criteria andUserActiveGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_ACTIVE >=", value, "userActive");
            return (Criteria) this;
        }

        public Criteria andUserActiveLessThan(BigDecimal value) {
            addCriterion("USER_ACTIVE <", value, "userActive");
            return (Criteria) this;
        }

        public Criteria andUserActiveLessThanOrEqualTo(BigDecimal value) {
            addCriterion("USER_ACTIVE <=", value, "userActive");
            return (Criteria) this;
        }

        public Criteria andUserActiveIn(List<BigDecimal> values) {
            addCriterion("USER_ACTIVE in", values, "userActive");
            return (Criteria) this;
        }

        public Criteria andUserActiveNotIn(List<BigDecimal> values) {
            addCriterion("USER_ACTIVE not in", values, "userActive");
            return (Criteria) this;
        }

        public Criteria andUserActiveBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_ACTIVE between", value1, value2, "userActive");
            return (Criteria) this;
        }

        public Criteria andUserActiveNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USER_ACTIVE not between", value1, value2, "userActive");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated do_not_delete_during_merge Fri Nov 01 16:10:21 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LS_USERS_INFO
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}