package cn.besbing.pojo;

import java.math.BigDecimal;

public class LsUsersInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LS_USERS_INFO.PK_PSNDOC
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    private String pkPsndoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LS_USERS_INFO.WORK_CODE
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    private String workCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LS_USERS_INFO.USER_NAME
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LS_USERS_INFO.USER_SEX
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    private BigDecimal userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LS_USERS_INFO.USER_PASSWD
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    private String userPasswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LS_USERS_INFO.USER_ACTIVE
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    private BigDecimal userActive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LS_USERS_INFO.PK_PSNDOC
     *
     * @return the value of LS_USERS_INFO.PK_PSNDOC
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public String getPkPsndoc() {
        return pkPsndoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LS_USERS_INFO.PK_PSNDOC
     *
     * @param pkPsndoc the value for LS_USERS_INFO.PK_PSNDOC
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public void setPkPsndoc(String pkPsndoc) {
        this.pkPsndoc = pkPsndoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LS_USERS_INFO.WORK_CODE
     *
     * @return the value of LS_USERS_INFO.WORK_CODE
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public String getWorkCode() {
        return workCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LS_USERS_INFO.WORK_CODE
     *
     * @param workCode the value for LS_USERS_INFO.WORK_CODE
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public void setWorkCode(String workCode) {
        this.workCode = workCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LS_USERS_INFO.USER_NAME
     *
     * @return the value of LS_USERS_INFO.USER_NAME
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LS_USERS_INFO.USER_NAME
     *
     * @param userName the value for LS_USERS_INFO.USER_NAME
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LS_USERS_INFO.USER_SEX
     *
     * @return the value of LS_USERS_INFO.USER_SEX
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public BigDecimal getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LS_USERS_INFO.USER_SEX
     *
     * @param userSex the value for LS_USERS_INFO.USER_SEX
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public void setUserSex(BigDecimal userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LS_USERS_INFO.USER_PASSWD
     *
     * @return the value of LS_USERS_INFO.USER_PASSWD
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public String getUserPasswd() {
        return userPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LS_USERS_INFO.USER_PASSWD
     *
     * @param userPasswd the value for LS_USERS_INFO.USER_PASSWD
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public void setUserPasswd(String userPasswd) {
        this.userPasswd = userPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LS_USERS_INFO.USER_ACTIVE
     *
     * @return the value of LS_USERS_INFO.USER_ACTIVE
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public BigDecimal getUserActive() {
        return userActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LS_USERS_INFO.USER_ACTIVE
     *
     * @param userActive the value for LS_USERS_INFO.USER_ACTIVE
     *
     * @mbg.generated Fri Nov 01 16:10:21 CST 2019
     */
    public void setUserActive(BigDecimal userActive) {
        this.userActive = userActive;
    }
}