package cn.besbing.pojo;

import java.math.BigDecimal;

public class SmUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.CUSERID
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String cuserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.ABLEDATE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String abledate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.BASE_DOC_TYPE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private BigDecimal baseDocType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.CONTENTLANG
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String contentlang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.CREATIONTIME
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String creationtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.CREATOR
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.DATAORIGINFLAG
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private BigDecimal dataoriginflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.DISABLEDATE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String disabledate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.DR
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private Long dr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.EMAIL
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.ENABLESTATE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private BigDecimal enablestate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.FORMAT
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String format;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.IDENTITYVERIFYCODE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String identityverifycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.ISCA
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String isca;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.ISLOCKED
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String islocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.MODIFIEDTIME
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String modifiedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.MODIFIER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.PK_BASE_DOC
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String pkBaseDoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.PK_CUSTOMER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String pkCustomer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.PK_GROUP
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String pkGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.PK_ORG
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String pkOrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.PK_PSNDOC
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String pkPsndoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.PK_SUPPLIER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String pkSupplier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.PK_USERGROUPFORCREATE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String pkUsergroupforcreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.PWDLEVELCODE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String pwdlevelcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.PWDPARAM
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String pwdparam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.SYSTYPE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String systype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.TS
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.USER_CODE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.USER_CODE_Q
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String userCodeQ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.USER_NAME
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.USER_NAME2
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String userName2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.USER_NAME3
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String userName3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.USER_NAME4
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String userName4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.USER_NAME5
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String userName5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.USER_NAME6
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String userName6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.USER_NOTE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String userNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.USER_PASSWORD
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_USER.USER_TYPE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    private BigDecimal userType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.CUSERID
     *
     * @return the value of SM_USER.CUSERID
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getCuserid() {
        return cuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.CUSERID
     *
     * @param cuserid the value for SM_USER.CUSERID
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setCuserid(String cuserid) {
        this.cuserid = cuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.ABLEDATE
     *
     * @return the value of SM_USER.ABLEDATE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getAbledate() {
        return abledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.ABLEDATE
     *
     * @param abledate the value for SM_USER.ABLEDATE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setAbledate(String abledate) {
        this.abledate = abledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.BASE_DOC_TYPE
     *
     * @return the value of SM_USER.BASE_DOC_TYPE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public BigDecimal getBaseDocType() {
        return baseDocType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.BASE_DOC_TYPE
     *
     * @param baseDocType the value for SM_USER.BASE_DOC_TYPE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setBaseDocType(BigDecimal baseDocType) {
        this.baseDocType = baseDocType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.CONTENTLANG
     *
     * @return the value of SM_USER.CONTENTLANG
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getContentlang() {
        return contentlang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.CONTENTLANG
     *
     * @param contentlang the value for SM_USER.CONTENTLANG
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setContentlang(String contentlang) {
        this.contentlang = contentlang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.CREATIONTIME
     *
     * @return the value of SM_USER.CREATIONTIME
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.CREATIONTIME
     *
     * @param creationtime the value for SM_USER.CREATIONTIME
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setCreationtime(String creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.CREATOR
     *
     * @return the value of SM_USER.CREATOR
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.CREATOR
     *
     * @param creator the value for SM_USER.CREATOR
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.DATAORIGINFLAG
     *
     * @return the value of SM_USER.DATAORIGINFLAG
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public BigDecimal getDataoriginflag() {
        return dataoriginflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.DATAORIGINFLAG
     *
     * @param dataoriginflag the value for SM_USER.DATAORIGINFLAG
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setDataoriginflag(BigDecimal dataoriginflag) {
        this.dataoriginflag = dataoriginflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.DISABLEDATE
     *
     * @return the value of SM_USER.DISABLEDATE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getDisabledate() {
        return disabledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.DISABLEDATE
     *
     * @param disabledate the value for SM_USER.DISABLEDATE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setDisabledate(String disabledate) {
        this.disabledate = disabledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.DR
     *
     * @return the value of SM_USER.DR
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public Long getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.DR
     *
     * @param dr the value for SM_USER.DR
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setDr(Long dr) {
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.EMAIL
     *
     * @return the value of SM_USER.EMAIL
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.EMAIL
     *
     * @param email the value for SM_USER.EMAIL
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.ENABLESTATE
     *
     * @return the value of SM_USER.ENABLESTATE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public BigDecimal getEnablestate() {
        return enablestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.ENABLESTATE
     *
     * @param enablestate the value for SM_USER.ENABLESTATE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setEnablestate(BigDecimal enablestate) {
        this.enablestate = enablestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.FORMAT
     *
     * @return the value of SM_USER.FORMAT
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.FORMAT
     *
     * @param format the value for SM_USER.FORMAT
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setFormat(String format) {
        this.format = format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.IDENTITYVERIFYCODE
     *
     * @return the value of SM_USER.IDENTITYVERIFYCODE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getIdentityverifycode() {
        return identityverifycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.IDENTITYVERIFYCODE
     *
     * @param identityverifycode the value for SM_USER.IDENTITYVERIFYCODE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setIdentityverifycode(String identityverifycode) {
        this.identityverifycode = identityverifycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.ISCA
     *
     * @return the value of SM_USER.ISCA
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getIsca() {
        return isca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.ISCA
     *
     * @param isca the value for SM_USER.ISCA
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setIsca(String isca) {
        this.isca = isca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.ISLOCKED
     *
     * @return the value of SM_USER.ISLOCKED
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getIslocked() {
        return islocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.ISLOCKED
     *
     * @param islocked the value for SM_USER.ISLOCKED
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setIslocked(String islocked) {
        this.islocked = islocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.MODIFIEDTIME
     *
     * @return the value of SM_USER.MODIFIEDTIME
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getModifiedtime() {
        return modifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.MODIFIEDTIME
     *
     * @param modifiedtime the value for SM_USER.MODIFIEDTIME
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setModifiedtime(String modifiedtime) {
        this.modifiedtime = modifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.MODIFIER
     *
     * @return the value of SM_USER.MODIFIER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.MODIFIER
     *
     * @param modifier the value for SM_USER.MODIFIER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.PK_BASE_DOC
     *
     * @return the value of SM_USER.PK_BASE_DOC
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getPkBaseDoc() {
        return pkBaseDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.PK_BASE_DOC
     *
     * @param pkBaseDoc the value for SM_USER.PK_BASE_DOC
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setPkBaseDoc(String pkBaseDoc) {
        this.pkBaseDoc = pkBaseDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.PK_CUSTOMER
     *
     * @return the value of SM_USER.PK_CUSTOMER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getPkCustomer() {
        return pkCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.PK_CUSTOMER
     *
     * @param pkCustomer the value for SM_USER.PK_CUSTOMER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setPkCustomer(String pkCustomer) {
        this.pkCustomer = pkCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.PK_GROUP
     *
     * @return the value of SM_USER.PK_GROUP
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getPkGroup() {
        return pkGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.PK_GROUP
     *
     * @param pkGroup the value for SM_USER.PK_GROUP
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setPkGroup(String pkGroup) {
        this.pkGroup = pkGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.PK_ORG
     *
     * @return the value of SM_USER.PK_ORG
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getPkOrg() {
        return pkOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.PK_ORG
     *
     * @param pkOrg the value for SM_USER.PK_ORG
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setPkOrg(String pkOrg) {
        this.pkOrg = pkOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.PK_PSNDOC
     *
     * @return the value of SM_USER.PK_PSNDOC
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getPkPsndoc() {
        return pkPsndoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.PK_PSNDOC
     *
     * @param pkPsndoc the value for SM_USER.PK_PSNDOC
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setPkPsndoc(String pkPsndoc) {
        this.pkPsndoc = pkPsndoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.PK_SUPPLIER
     *
     * @return the value of SM_USER.PK_SUPPLIER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getPkSupplier() {
        return pkSupplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.PK_SUPPLIER
     *
     * @param pkSupplier the value for SM_USER.PK_SUPPLIER
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setPkSupplier(String pkSupplier) {
        this.pkSupplier = pkSupplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.PK_USERGROUPFORCREATE
     *
     * @return the value of SM_USER.PK_USERGROUPFORCREATE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getPkUsergroupforcreate() {
        return pkUsergroupforcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.PK_USERGROUPFORCREATE
     *
     * @param pkUsergroupforcreate the value for SM_USER.PK_USERGROUPFORCREATE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setPkUsergroupforcreate(String pkUsergroupforcreate) {
        this.pkUsergroupforcreate = pkUsergroupforcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.PWDLEVELCODE
     *
     * @return the value of SM_USER.PWDLEVELCODE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getPwdlevelcode() {
        return pwdlevelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.PWDLEVELCODE
     *
     * @param pwdlevelcode the value for SM_USER.PWDLEVELCODE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setPwdlevelcode(String pwdlevelcode) {
        this.pwdlevelcode = pwdlevelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.PWDPARAM
     *
     * @return the value of SM_USER.PWDPARAM
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getPwdparam() {
        return pwdparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.PWDPARAM
     *
     * @param pwdparam the value for SM_USER.PWDPARAM
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setPwdparam(String pwdparam) {
        this.pwdparam = pwdparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.SYSTYPE
     *
     * @return the value of SM_USER.SYSTYPE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getSystype() {
        return systype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.SYSTYPE
     *
     * @param systype the value for SM_USER.SYSTYPE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setSystype(String systype) {
        this.systype = systype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.TS
     *
     * @return the value of SM_USER.TS
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.TS
     *
     * @param ts the value for SM_USER.TS
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setTs(String ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.USER_CODE
     *
     * @return the value of SM_USER.USER_CODE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.USER_CODE
     *
     * @param userCode the value for SM_USER.USER_CODE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.USER_CODE_Q
     *
     * @return the value of SM_USER.USER_CODE_Q
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getUserCodeQ() {
        return userCodeQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.USER_CODE_Q
     *
     * @param userCodeQ the value for SM_USER.USER_CODE_Q
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setUserCodeQ(String userCodeQ) {
        this.userCodeQ = userCodeQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.USER_NAME
     *
     * @return the value of SM_USER.USER_NAME
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.USER_NAME
     *
     * @param userName the value for SM_USER.USER_NAME
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.USER_NAME2
     *
     * @return the value of SM_USER.USER_NAME2
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getUserName2() {
        return userName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.USER_NAME2
     *
     * @param userName2 the value for SM_USER.USER_NAME2
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setUserName2(String userName2) {
        this.userName2 = userName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.USER_NAME3
     *
     * @return the value of SM_USER.USER_NAME3
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getUserName3() {
        return userName3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.USER_NAME3
     *
     * @param userName3 the value for SM_USER.USER_NAME3
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setUserName3(String userName3) {
        this.userName3 = userName3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.USER_NAME4
     *
     * @return the value of SM_USER.USER_NAME4
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getUserName4() {
        return userName4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.USER_NAME4
     *
     * @param userName4 the value for SM_USER.USER_NAME4
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setUserName4(String userName4) {
        this.userName4 = userName4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.USER_NAME5
     *
     * @return the value of SM_USER.USER_NAME5
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getUserName5() {
        return userName5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.USER_NAME5
     *
     * @param userName5 the value for SM_USER.USER_NAME5
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setUserName5(String userName5) {
        this.userName5 = userName5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.USER_NAME6
     *
     * @return the value of SM_USER.USER_NAME6
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getUserName6() {
        return userName6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.USER_NAME6
     *
     * @param userName6 the value for SM_USER.USER_NAME6
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setUserName6(String userName6) {
        this.userName6 = userName6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.USER_NOTE
     *
     * @return the value of SM_USER.USER_NOTE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getUserNote() {
        return userNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.USER_NOTE
     *
     * @param userNote the value for SM_USER.USER_NOTE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setUserNote(String userNote) {
        this.userNote = userNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.USER_PASSWORD
     *
     * @return the value of SM_USER.USER_PASSWORD
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.USER_PASSWORD
     *
     * @param userPassword the value for SM_USER.USER_PASSWORD
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_USER.USER_TYPE
     *
     * @return the value of SM_USER.USER_TYPE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public BigDecimal getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_USER.USER_TYPE
     *
     * @param userType the value for SM_USER.USER_TYPE
     *
     * @mbg.generated Fri Nov 01 10:52:57 CST 2019
     */
    public void setUserType(BigDecimal userType) {
        this.userType = userType;
    }
}